export const ON_ERROR = 'ON_ERROR';

export const ON_INSERT = 'ON_INSERT';
export const ON_SUCCESS_INSERT = 'ON_SUCCESS_INSERT';

export const ON_QUERY = 'ON_QUERY';
export const ON_SUCCESS_QUERY = 'ON_SUCCESS_QUERY';

export const ON_RESERVATIONS = 'ON_RESERVATIONS';
export const ON_SUCCESS_RESERVATIONS = 'ON_SUCCESS_RESERVATIONS';

export const ON_SELECT_RESERVATION = 'ON_SELECT_RESERVATION';
export const ON_DISSELECT_RESERVATION = 'ON_DISSELECT_RESERVATION';

export const ON_DELETE = 'ON_DELETE';
export const ON_SUCCESS_DELETE = 'ON_SUCCESS_DELETE';

export const ON_DETAIL_SELECTED = 'ON_DETAIL_SELECTED';
export const ON_DETAIL_DISSELECTED = 'ON_DETAIL_DISSELECTED';

export const ON_REGISTER = 'ON_REGISTER';
export const ON_SUCCESS_REGISTER = 'ON_SUCCESS_REGISTER';

export const ON_UPDATE = 'ON_UPDATE';
export const ON_SUCCESS_UPDATE = 'ON_SUCCESS_UPDATE';